API:
  LARGE_API_KEY: key-here
  LARGE_MODEL: meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo
  LARGE_BASE_URL: https://api.together.xyz
  LARGE_MODE: api
  SMALL_MODEL: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
  SMALL_BASE_URL: https://api.together.xyz
  SMALL_API_KEY: key-here
  SMALL_MODE: api
HUGGINGFACE:
  HUB_PATH: yourusername/your-path-here
  PRIVATE: false
  PUSH_TO_HUB: false
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./input_philosophy_top5
  OUTPUT: ./output_philosophy_top5_negative
  PROMPTS: ./prompt_overrides/prompts_override_negative_questions
PHASE:
  PHASE_INDEX: 3
  WORK_IN_PHASES: false
SKIP:
  ANSWER_RELEVANCY_CHECK: true
  REPAIR_QA_TUPLES: false
  FILTER_CHUNKS: false
  QUESTION_CHECK: false
  CONVERSATION_GENERATION: false
SYSTEM:
  CHUNK_SIZE: 1900
  COMPLETION_MODE: false
  CONCURRENCY_LIMIT: 50
  CONVERSATION_INSTRUCTIONS: For this conversation, you are generating a chat between
    a generalist, generic AI assistant, and a human.
  DOUBLE_CHECK_COUNTER: 1
  DO_NOT_USE_SYSTEM_PROMPTS: true
  FINAL_ASSISTANT_PROMPTS_NO_RAG:
  - You are a helpful AI assistant.
  - 'You are A VASTLY intelligent ARTIFICIAL INTELLIGENCE with DOMAIN-EXPERT KNOWLEDGE
    from a variety of fields.

    USE your knowledge to be helpful and truthfully answer questions about the world.'
  - u are ai asstant plz answr questions
  FINAL_ASSISTANT_PROMPTS_RAG:
  - 'You are a helpful AI assistant. Some knowledge:

    {data}'
  - '{data}

    You are an AI domain expert. Answer questions'
  - 'You are an AI with vast knowledge. Here is some potentially-relevant context:

    {data}

    Answer questions according to your knowledge.'
  STOP: true
  SUBSET_SIZE: 20
  USE_FILENAMES: false
  USE_SUBSET: false
  RAG_FAILURE_PERCENTAGE: 0.1
SCRAPING:
  USE_GUTENBERG: true
  START_URL: https://www.gutenberg.org/ebooks/bookshelf/57
  MAX_BOOKS: 5
  MAX_FAILURES: 5
