API:
  API_KEY_A: aphrodite-needs-a-dummy-key
  API_KEY_B: not_used_anyway
  BASE_URL_A: http://localhost:2242/v1 # default aphrodite URL
  BASE_URL_B: http://localhost:2242/v1
  LOGICAL_MODEL_A: ./Mistral-Large-Instruct-2407-123B-exl2/ # This model seems to write alright. Questionable license though. Consider llamas, or RP finetunes? But instruction following is key -- magnun 72b by anthracite did really poorly.
  LOGICAL_MODEL_B: ./Mistral-Large-Instruct-2407-123B-exl2/
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./raw_txt_input
  OUTPUT: ./output
  PROMPTS: ./prompts
PHASES:
  PHASE_INDEX: 2
  WORK_IN_PHASES: False
SYSTEM:
  COMPLETION_MODE: False
  CONCURRENCY_LIMIT: 50
  EMOTIONS: ['FEARLESSNESS', 'LUST', 'EMBARASSMENT', 'NIHILISM',
    'DETERMINATION', 'DESPERATION', 'LOSS', 'NOSTALGIA', 'ANTICIPATION',
    'TRUST', 'FEAR', 'DISORIENTATION', 'DEGRADATION']
  INCLUDE_CHUNK_IN_PROMPT: True
  MODE_A: api
  MODE_B: api
  PICK_EMOTION: True
  RP_PROMPT_END: ''
  RP_PROMPT_START: ''
  STOP: True
  SUBSET_SIZE: 10
  USE_MIN_P: False
  USE_SUBSET: False
  CHUNK_SIZE: 1500
